/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLiveOperationsRouteImport } from './routes/_authenticated/live-operations'
import { Route as AuthenticatedFuelExpensesRouteImport } from './routes/_authenticated/fuel-expenses'
import { Route as AuthenticatedFleetHealthRouteImport } from './routes/_authenticated/fleet-health'
import { Route as AuthenticatedDispatchIntelligenceRouteImport } from './routes/_authenticated/dispatch-intelligence'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance.index'
import { Route as AuthenticatedFleetIndexRouteImport } from './routes/_authenticated/fleet.index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers.index'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated/trips.new'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as AuthenticatedMaintenanceNewRouteImport } from './routes/_authenticated/maintenance.new'
import { Route as AuthenticatedMaintenanceMaintenanceIdRouteImport } from './routes/_authenticated/maintenance.$maintenanceId'
import { Route as AuthenticatedFleetNewRouteImport } from './routes/_authenticated/fleet.new'
import { Route as AuthenticatedFleetVehicleIdRouteImport } from './routes/_authenticated/fleet.$vehicleId'
import { Route as AuthenticatedDriversNewRouteImport } from './routes/_authenticated/drivers.new'
import { Route as AuthenticatedDriversDriverIdRouteImport } from './routes/_authenticated/drivers.$driverId'
import { Route as AuthenticatedTripsTripIdEditRouteImport } from './routes/_authenticated/trips.$tripId.edit'
import { Route as AuthenticatedMaintenanceMaintenanceIdEditRouteImport } from './routes/_authenticated/maintenance.$maintenanceId.edit'
import { Route as AuthenticatedFleetVehicleIdEditRouteImport } from './routes/_authenticated/fleet.$vehicleId.edit'
import { Route as AuthenticatedDriversDriverIdEditRouteImport } from './routes/_authenticated/drivers.$driverId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLiveOperationsRoute =
  AuthenticatedLiveOperationsRouteImport.update({
    id: '/live-operations',
    path: '/live-operations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFuelExpensesRoute =
  AuthenticatedFuelExpensesRouteImport.update({
    id: '/fuel-expenses',
    path: '/fuel-expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFleetHealthRoute =
  AuthenticatedFleetHealthRouteImport.update({
    id: '/fleet-health',
    path: '/fleet-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchIntelligenceRoute =
  AuthenticatedDispatchIntelligenceRouteImport.update({
    id: '/dispatch-intelligence',
    path: '/dispatch-intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFleetIndexRoute = AuthenticatedFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceNewRoute =
  AuthenticatedMaintenanceNewRouteImport.update({
    id: '/maintenance/new',
    path: '/maintenance/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceMaintenanceIdRoute =
  AuthenticatedMaintenanceMaintenanceIdRouteImport.update({
    id: '/maintenance/$maintenanceId',
    path: '/maintenance/$maintenanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFleetNewRoute = AuthenticatedFleetNewRouteImport.update({
  id: '/fleet/new',
  path: '/fleet/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetVehicleIdRoute =
  AuthenticatedFleetVehicleIdRouteImport.update({
    id: '/fleet/$vehicleId',
    path: '/fleet/$vehicleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriversNewRoute = AuthenticatedDriversNewRouteImport.update({
  id: '/drivers/new',
  path: '/drivers/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversDriverIdRoute =
  AuthenticatedDriversDriverIdRouteImport.update({
    id: '/drivers/$driverId',
    path: '/drivers/$driverId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsTripIdEditRoute =
  AuthenticatedTripsTripIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedMaintenanceMaintenanceIdEditRoute =
  AuthenticatedMaintenanceMaintenanceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMaintenanceMaintenanceIdRoute,
  } as any)
const AuthenticatedFleetVehicleIdEditRoute =
  AuthenticatedFleetVehicleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedFleetVehicleIdRoute,
  } as any)
const AuthenticatedDriversDriverIdEditRoute =
  AuthenticatedDriversDriverIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDriversDriverIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch-intelligence': typeof AuthenticatedDispatchIntelligenceRoute
  '/fleet-health': typeof AuthenticatedFleetHealthRoute
  '/fuel-expenses': typeof AuthenticatedFuelExpensesRoute
  '/live-operations': typeof AuthenticatedLiveOperationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AuthenticatedDriversNewRoute
  '/fleet/$vehicleId': typeof AuthenticatedFleetVehicleIdRouteWithChildren
  '/fleet/new': typeof AuthenticatedFleetNewRoute
  '/maintenance/$maintenanceId': typeof AuthenticatedMaintenanceMaintenanceIdRouteWithChildren
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/fleet/': typeof AuthenticatedFleetIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/drivers/$driverId/edit': typeof AuthenticatedDriversDriverIdEditRoute
  '/fleet/$vehicleId/edit': typeof AuthenticatedFleetVehicleIdEditRoute
  '/maintenance/$maintenanceId/edit': typeof AuthenticatedMaintenanceMaintenanceIdEditRoute
  '/trips/$tripId/edit': typeof AuthenticatedTripsTripIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch-intelligence': typeof AuthenticatedDispatchIntelligenceRoute
  '/fleet-health': typeof AuthenticatedFleetHealthRoute
  '/fuel-expenses': typeof AuthenticatedFuelExpensesRoute
  '/live-operations': typeof AuthenticatedLiveOperationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AuthenticatedDriversNewRoute
  '/fleet/$vehicleId': typeof AuthenticatedFleetVehicleIdRouteWithChildren
  '/fleet/new': typeof AuthenticatedFleetNewRoute
  '/maintenance/$maintenanceId': typeof AuthenticatedMaintenanceMaintenanceIdRouteWithChildren
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/drivers/$driverId/edit': typeof AuthenticatedDriversDriverIdEditRoute
  '/fleet/$vehicleId/edit': typeof AuthenticatedFleetVehicleIdEditRoute
  '/maintenance/$maintenanceId/edit': typeof AuthenticatedMaintenanceMaintenanceIdEditRoute
  '/trips/$tripId/edit': typeof AuthenticatedTripsTripIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispatch-intelligence': typeof AuthenticatedDispatchIntelligenceRoute
  '/_authenticated/fleet-health': typeof AuthenticatedFleetHealthRoute
  '/_authenticated/fuel-expenses': typeof AuthenticatedFuelExpensesRoute
  '/_authenticated/live-operations': typeof AuthenticatedLiveOperationsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/drivers/$driverId': typeof AuthenticatedDriversDriverIdRouteWithChildren
  '/_authenticated/drivers/new': typeof AuthenticatedDriversNewRoute
  '/_authenticated/fleet/$vehicleId': typeof AuthenticatedFleetVehicleIdRouteWithChildren
  '/_authenticated/fleet/new': typeof AuthenticatedFleetNewRoute
  '/_authenticated/maintenance/$maintenanceId': typeof AuthenticatedMaintenanceMaintenanceIdRouteWithChildren
  '/_authenticated/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/fleet/': typeof AuthenticatedFleetIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/drivers/$driverId/edit': typeof AuthenticatedDriversDriverIdEditRoute
  '/_authenticated/fleet/$vehicleId/edit': typeof AuthenticatedFleetVehicleIdEditRoute
  '/_authenticated/maintenance/$maintenanceId/edit': typeof AuthenticatedMaintenanceMaintenanceIdEditRoute
  '/_authenticated/trips/$tripId/edit': typeof AuthenticatedTripsTripIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/dispatch-intelligence'
    | '/fleet-health'
    | '/fuel-expenses'
    | '/live-operations'
    | '/notifications'
    | '/settings'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/fleet/$vehicleId'
    | '/fleet/new'
    | '/maintenance/$maintenanceId'
    | '/maintenance/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/drivers/'
    | '/fleet/'
    | '/maintenance/'
    | '/trips/'
    | '/drivers/$driverId/edit'
    | '/fleet/$vehicleId/edit'
    | '/maintenance/$maintenanceId/edit'
    | '/trips/$tripId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/dispatch-intelligence'
    | '/fleet-health'
    | '/fuel-expenses'
    | '/live-operations'
    | '/notifications'
    | '/settings'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/fleet/$vehicleId'
    | '/fleet/new'
    | '/maintenance/$maintenanceId'
    | '/maintenance/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/drivers'
    | '/fleet'
    | '/maintenance'
    | '/trips'
    | '/drivers/$driverId/edit'
    | '/fleet/$vehicleId/edit'
    | '/maintenance/$maintenanceId/edit'
    | '/trips/$tripId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispatch-intelligence'
    | '/_authenticated/fleet-health'
    | '/_authenticated/fuel-expenses'
    | '/_authenticated/live-operations'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/drivers/$driverId'
    | '/_authenticated/drivers/new'
    | '/_authenticated/fleet/$vehicleId'
    | '/_authenticated/fleet/new'
    | '/_authenticated/maintenance/$maintenanceId'
    | '/_authenticated/maintenance/new'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/new'
    | '/_authenticated/drivers/'
    | '/_authenticated/fleet/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/trips/'
    | '/_authenticated/drivers/$driverId/edit'
    | '/_authenticated/fleet/$vehicleId/edit'
    | '/_authenticated/maintenance/$maintenanceId/edit'
    | '/_authenticated/trips/$tripId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live-operations': {
      id: '/_authenticated/live-operations'
      path: '/live-operations'
      fullPath: '/live-operations'
      preLoaderRoute: typeof AuthenticatedLiveOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fuel-expenses': {
      id: '/_authenticated/fuel-expenses'
      path: '/fuel-expenses'
      fullPath: '/fuel-expenses'
      preLoaderRoute: typeof AuthenticatedFuelExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet-health': {
      id: '/_authenticated/fleet-health'
      path: '/fleet-health'
      fullPath: '/fleet-health'
      preLoaderRoute: typeof AuthenticatedFleetHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-intelligence': {
      id: '/_authenticated/dispatch-intelligence'
      path: '/dispatch-intelligence'
      fullPath: '/dispatch-intelligence'
      preLoaderRoute: typeof AuthenticatedDispatchIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet/': {
      id: '/_authenticated/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AuthenticatedFleetIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/new': {
      id: '/_authenticated/maintenance/new'
      path: '/maintenance/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof AuthenticatedMaintenanceNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/$maintenanceId': {
      id: '/_authenticated/maintenance/$maintenanceId'
      path: '/maintenance/$maintenanceId'
      fullPath: '/maintenance/$maintenanceId'
      preLoaderRoute: typeof AuthenticatedMaintenanceMaintenanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet/new': {
      id: '/_authenticated/fleet/new'
      path: '/fleet/new'
      fullPath: '/fleet/new'
      preLoaderRoute: typeof AuthenticatedFleetNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet/$vehicleId': {
      id: '/_authenticated/fleet/$vehicleId'
      path: '/fleet/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof AuthenticatedFleetVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers/new': {
      id: '/_authenticated/drivers/new'
      path: '/drivers/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof AuthenticatedDriversNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers/$driverId': {
      id: '/_authenticated/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/$tripId/edit': {
      id: '/_authenticated/trips/$tripId/edit'
      path: '/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof AuthenticatedTripsTripIdEditRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/maintenance/$maintenanceId/edit': {
      id: '/_authenticated/maintenance/$maintenanceId/edit'
      path: '/edit'
      fullPath: '/maintenance/$maintenanceId/edit'
      preLoaderRoute: typeof AuthenticatedMaintenanceMaintenanceIdEditRouteImport
      parentRoute: typeof AuthenticatedMaintenanceMaintenanceIdRoute
    }
    '/_authenticated/fleet/$vehicleId/edit': {
      id: '/_authenticated/fleet/$vehicleId/edit'
      path: '/edit'
      fullPath: '/fleet/$vehicleId/edit'
      preLoaderRoute: typeof AuthenticatedFleetVehicleIdEditRouteImport
      parentRoute: typeof AuthenticatedFleetVehicleIdRoute
    }
    '/_authenticated/drivers/$driverId/edit': {
      id: '/_authenticated/drivers/$driverId/edit'
      path: '/edit'
      fullPath: '/drivers/$driverId/edit'
      preLoaderRoute: typeof AuthenticatedDriversDriverIdEditRouteImport
      parentRoute: typeof AuthenticatedDriversDriverIdRoute
    }
  }
}

interface AuthenticatedDriversDriverIdRouteChildren {
  AuthenticatedDriversDriverIdEditRoute: typeof AuthenticatedDriversDriverIdEditRoute
}

const AuthenticatedDriversDriverIdRouteChildren: AuthenticatedDriversDriverIdRouteChildren =
  {
    AuthenticatedDriversDriverIdEditRoute:
      AuthenticatedDriversDriverIdEditRoute,
  }

const AuthenticatedDriversDriverIdRouteWithChildren =
  AuthenticatedDriversDriverIdRoute._addFileChildren(
    AuthenticatedDriversDriverIdRouteChildren,
  )

interface AuthenticatedFleetVehicleIdRouteChildren {
  AuthenticatedFleetVehicleIdEditRoute: typeof AuthenticatedFleetVehicleIdEditRoute
}

const AuthenticatedFleetVehicleIdRouteChildren: AuthenticatedFleetVehicleIdRouteChildren =
  {
    AuthenticatedFleetVehicleIdEditRoute: AuthenticatedFleetVehicleIdEditRoute,
  }

const AuthenticatedFleetVehicleIdRouteWithChildren =
  AuthenticatedFleetVehicleIdRoute._addFileChildren(
    AuthenticatedFleetVehicleIdRouteChildren,
  )

interface AuthenticatedMaintenanceMaintenanceIdRouteChildren {
  AuthenticatedMaintenanceMaintenanceIdEditRoute: typeof AuthenticatedMaintenanceMaintenanceIdEditRoute
}

const AuthenticatedMaintenanceMaintenanceIdRouteChildren: AuthenticatedMaintenanceMaintenanceIdRouteChildren =
  {
    AuthenticatedMaintenanceMaintenanceIdEditRoute:
      AuthenticatedMaintenanceMaintenanceIdEditRoute,
  }

const AuthenticatedMaintenanceMaintenanceIdRouteWithChildren =
  AuthenticatedMaintenanceMaintenanceIdRoute._addFileChildren(
    AuthenticatedMaintenanceMaintenanceIdRouteChildren,
  )

interface AuthenticatedTripsTripIdRouteChildren {
  AuthenticatedTripsTripIdEditRoute: typeof AuthenticatedTripsTripIdEditRoute
}

const AuthenticatedTripsTripIdRouteChildren: AuthenticatedTripsTripIdRouteChildren =
  {
    AuthenticatedTripsTripIdEditRoute: AuthenticatedTripsTripIdEditRoute,
  }

const AuthenticatedTripsTripIdRouteWithChildren =
  AuthenticatedTripsTripIdRoute._addFileChildren(
    AuthenticatedTripsTripIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispatchIntelligenceRoute: typeof AuthenticatedDispatchIntelligenceRoute
  AuthenticatedFleetHealthRoute: typeof AuthenticatedFleetHealthRoute
  AuthenticatedFuelExpensesRoute: typeof AuthenticatedFuelExpensesRoute
  AuthenticatedLiveOperationsRoute: typeof AuthenticatedLiveOperationsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDriversDriverIdRoute: typeof AuthenticatedDriversDriverIdRouteWithChildren
  AuthenticatedDriversNewRoute: typeof AuthenticatedDriversNewRoute
  AuthenticatedFleetVehicleIdRoute: typeof AuthenticatedFleetVehicleIdRouteWithChildren
  AuthenticatedFleetNewRoute: typeof AuthenticatedFleetNewRoute
  AuthenticatedMaintenanceMaintenanceIdRoute: typeof AuthenticatedMaintenanceMaintenanceIdRouteWithChildren
  AuthenticatedMaintenanceNewRoute: typeof AuthenticatedMaintenanceNewRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRouteWithChildren
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedFleetIndexRoute: typeof AuthenticatedFleetIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispatchIntelligenceRoute:
    AuthenticatedDispatchIntelligenceRoute,
  AuthenticatedFleetHealthRoute: AuthenticatedFleetHealthRoute,
  AuthenticatedFuelExpensesRoute: AuthenticatedFuelExpensesRoute,
  AuthenticatedLiveOperationsRoute: AuthenticatedLiveOperationsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDriversDriverIdRoute:
    AuthenticatedDriversDriverIdRouteWithChildren,
  AuthenticatedDriversNewRoute: AuthenticatedDriversNewRoute,
  AuthenticatedFleetVehicleIdRoute:
    AuthenticatedFleetVehicleIdRouteWithChildren,
  AuthenticatedFleetNewRoute: AuthenticatedFleetNewRoute,
  AuthenticatedMaintenanceMaintenanceIdRoute:
    AuthenticatedMaintenanceMaintenanceIdRouteWithChildren,
  AuthenticatedMaintenanceNewRoute: AuthenticatedMaintenanceNewRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRouteWithChildren,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedFleetIndexRoute: AuthenticatedFleetIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
