export const queryKeys = {
  vehicles: ["vehicles"] as const,
  vehicle: (id: string) => ["vehicle", id] as const,
  eligibleVehicles: ["vehicles", "dispatch-eligible"] as const,
  drivers: ["drivers"] as const,
  driver: (id: string) => ["driver", id] as const,
  eligibleDrivers: ["drivers", "dispatch-eligible"] as const,
  trips: ["trips"] as const,
  trip: (id: string) => ["trip", id] as const,
  maintenance: ["maintenance"] as const,
  fuel: ["fuel"] as const,
  expenses: ["expenses"] as const,
  notifications: ["notifications"] as const,
  dashboard: ["dashboard-kpis"] as const,
  locations: ["locations"] as const,
  analyticsSummary: ["analytics-summary"] as const,
  analyticsByVehicle: ["analytics-by-vehicle"] as const,
  settings: ["settings"] as const,
  users: ["users"] as const,
  regions: ["regions"] as const,
  vehicleTypes: ["vehicle-types"] as const,
  licenceCategories: ["licence-categories"] as const,
};
